version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: .   # 👈 uses the Dockerfile in current directory
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
